# CNB æµæ°´çº¿é…ç½® - ç£åŠ›é“¾æŽ¥ä¸‹è½½åˆ° OneDrive
# é€šè¿‡ api_trigger äº‹ä»¶è§¦å‘

main:
  # API è§¦å‘äº‹ä»¶ - ç”¨äºŽç£åŠ›é“¾æŽ¥ä¸‹è½½
  api_trigger_magnet:
    - name: magnet-download
      docker:
        image: ubuntu:22.04
      stages:
        - name: Install dependencies
          script: |
            apt-get update
            apt-get install -y aria2 nodejs npm curl
            npm install axios

        - name: Get Latest Trackers
          script: |
            echo "ðŸ“¡ Fetching latest tracker list..."
            TRACKERS=$(curl -fsSL https://cf.trackerslist.com/best_aria2.txt || curl -fsSL https://raw.githubusercontent.com/XIU2/TrackersListCollection/master/best_aria2.txt)
            echo "TRACKERS=$TRACKERS" >> $GITHUB_ENV
            echo "##[set-output trackers=$TRACKERS]"

        - name: Download and Upload
          script: node stream_upload.js
