# CNB æµæ°´çº¿é…ç½® - ç£åŠ›é“¾æŽ¥ä¸‹è½½åˆ° OneDrive

"**":
  api_trigger_magnet:
    - name: magnet-download-test
      docker:
        image: node:20-slim
      stages:
        - name: Install aria2
          script: |
            sed -i 's/deb.debian.org/mirrors.cloud.tencent.com/g' /etc/apt/sources.list.d/debian.sources 2>/dev/null || true
            apt-get update && apt-get install -y --no-install-recommends aria2 curl

        - name: Get trackers
          script: |
            echo "ðŸ“¡ èšåˆèŽ·å– Tracker åˆ—è¡¨..."
            ALL_TRACKERS=""
            
            # æº1: adysec (æœ€å…¨)
            echo "ðŸ”¹ [1/5] adysec/tracker..."
            ADYSEC=$(curl -fsSL --connect-timeout 15 "https://raw.githubusercontent.com/adysec/tracker/main/tracker_all.txt" 2>/dev/null | grep -v '^$' | tr '\n' ',' | sed 's/,$//' || echo "")
            if [ -n "$ADYSEC" ]; then
              ALL_TRACKERS="$ADYSEC"
              echo "   âœ… adysec: $(echo "$ADYSEC" | tr ',' '\n' | grep -v '^$' | wc -l) trackers"
            fi
            
            # æº2: XIU2 all
            echo "ðŸ”¹ [2/5] XIU2/TrackersListCollection (all)..."
            XIU2=$(curl -fsSL --connect-timeout 15 "https://raw.githubusercontent.com/XIU2/TrackersListCollection/master/all.txt" 2>/dev/null | grep -v '^$' | tr '\n' ',' | sed 's/,$//' || echo "")
            if [ -n "$XIU2" ]; then
              [ -n "$ALL_TRACKERS" ] && ALL_TRACKERS="${ALL_TRACKERS},${XIU2}" || ALL_TRACKERS="$XIU2"
              echo "   âœ… XIU2 all: $(echo "$XIU2" | tr ',' '\n' | grep -v '^$' | wc -l) trackers"
            fi
            
            # æº3: XIU2 http
            echo "ðŸ”¹ [3/5] XIU2 (http)..."
            XIU2_HTTP=$(curl -fsSL --connect-timeout 15 "https://raw.githubusercontent.com/XIU2/TrackersListCollection/master/http.txt" 2>/dev/null | grep -v '^$' | tr '\n' ',' | sed 's/,$//' || echo "")
            if [ -n "$XIU2_HTTP" ]; then
              [ -n "$ALL_TRACKERS" ] && ALL_TRACKERS="${ALL_TRACKERS},${XIU2_HTTP}" || ALL_TRACKERS="$XIU2_HTTP"
              echo "   âœ… XIU2 http: $(echo "$XIU2_HTTP" | tr ',' '\n' | grep -v '^$' | wc -l) trackers"
            fi
            
            # æº4: ngosang all
            echo "ðŸ”¹ [4/5] ngosang/trackerslist..."
            NGOSANG=$(curl -fsSL --connect-timeout 15 "https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt" 2>/dev/null | grep -v '^$' | tr '\n' ',' | sed 's/,$//' || echo "")
            if [ -n "$NGOSANG" ]; then
              [ -n "$ALL_TRACKERS" ] && ALL_TRACKERS="${ALL_TRACKERS},${NGOSANG}" || ALL_TRACKERS="$NGOSANG"
              echo "   âœ… ngosang: $(echo "$NGOSANG" | tr ',' '\n' | grep -v '^$' | wc -l) trackers"
            fi
            
            # æº5: å¤‡ç”¨ç¡¬ç¼–ç 
            echo "ðŸ”¹ [5/5] å¤‡ç”¨åˆ—è¡¨..."
            BACKUP="udp://tracker.opentrackr.org:1337/announce,udp://open.stealth.si:80/announce,udp://tracker.torrent.eu.org:451/announce,udp://exodus.desync.com:6969/announce,udp://tracker.openbittorrent.com:6969/announce,udp://explodie.org:6969/announce,udp://bt1.archive.org:6969/announce,udp://bt2.archive.org:6969/announce,udp://tracker.opentrackr.org:1337,udp://open.demonii.com:1337/announce,udp://tracker.coppersurfer.tk:6969/announce,udp://tracker.leechers-paradise.org:6969/announce,http://tracker.bt4g.com:2095/announce"
            [ -n "$ALL_TRACKERS" ] && ALL_TRACKERS="${ALL_TRACKERS},${BACKUP}" || ALL_TRACKERS="$BACKUP"
            
            # åŽ»é‡
            BEFORE=$(echo "$ALL_TRACKERS" | tr ',' '\n' | grep -v '^$' | wc -l)
            ALL_TRACKERS=$(echo "$ALL_TRACKERS" | tr ',' '\n' | grep -v '^$' | sort -u | tr '\n' ',' | sed 's/,$//')
            AFTER=$(echo "$ALL_TRACKERS" | tr ',' '\n' | grep -v '^$' | wc -l)
            echo "ðŸ“Š åŽ»é‡: $BEFORE â†’ $AFTER ä¸ªå”¯ä¸€ Tracker"
            
            echo "$ALL_TRACKERS" > /tmp/trackers.txt
            echo "âœ… Tracker åˆ—è¡¨å·²ä¿å­˜"

        - name: Download magnet
          script: |
            echo "ðŸš€ Starting aria2 download..."
            echo "ðŸ“¥ MAGNET: $MAGNET"
            echo ""
            
            TRACKERS=$(cat /tmp/trackers.txt)
            TRACKER_COUNT=$(echo "$TRACKERS" | tr ',' '\n' | grep -v '^$' | wc -l)
            echo "ðŸ“¡ Using $TRACKER_COUNT trackers"
            echo ""
            
            mkdir -p /downloads
            
            # ä½¿ç”¨ --show-console-readout æ˜¾ç¤ºè¯¦ç»†è¿›åº¦
            aria2c "$MAGNET" \
              --dir=/downloads \
              --bt-tracker="$TRACKERS" \
              --bt-max-peers=200 \
              --max-connection-per-server=16 \
              --split=16 \
              --min-split-size=1M \
              --file-allocation=none \
              --seed-time=0 \
              --check-integrity=true \
              --continue=true \
              --max-concurrent-downloads=5 \
              --enable-dht=true \
              --enable-peer-exchange=true \
              --bt-enable-lpd=true \
              --bt-request-peer-speed-limit=10M \
              --summary-interval=5 \
              --bt-stop-timeout=900 \
              --console-log-level=notice \
              --show-console-readout=true \
              --human-readable=true \
              --download-result=full || echo "Download finished or timeout"
            
            echo ""
            echo "=========================================="
            echo "ðŸ“ Downloaded files:"
            ls -lah /downloads/
            echo ""
            echo "ðŸ“Š Total size:"
            du -sh /downloads/* 2>/dev/null || echo "No files downloaded"
            echo "=========================================="
