# CNB æµæ°´çº¿é…ç½® - ç£åŠ›é“¾æŽ¥ä¸‹è½½åˆ° OneDrive
# é€šè¿‡ api_trigger äº‹ä»¶è§¦å‘

# åŒ¹é…æ‰€æœ‰åˆ†æ”¯
"**":
  # API è§¦å‘äº‹ä»¶ - ç”¨äºŽç£åŠ›é“¾æŽ¥ä¸‹è½½
  api_trigger_magnet:
    - name: magnet-download
      docker:
        # ä½¿ç”¨ Node.js é•œåƒï¼Œè‡ªå¸¦ node å’Œ npmï¼ŒçœåŽ»å®‰è£…æ—¶é—´
        image: node:20-slim
      stages:
        - name: Install aria2
          script: |
            # ä½¿ç”¨è…¾è®¯äº‘é•œåƒæºåŠ é€Ÿ
            sed -i 's/deb.debian.org/mirrors.cloud.tencent.com/g' /etc/apt/sources.list.d/debian.sources 2>/dev/null || \
            sed -i 's/deb.debian.org/mirrors.cloud.tencent.com/g' /etc/apt/sources.list 2>/dev/null || true
            apt-get update && apt-get install -y --no-install-recommends aria2 curl
            npm install axios

        - name: Get Trackers and Download
          script: |
            echo "ðŸ“¡ Fetching trackers..."
            export BT_TRACKERS=$(curl -fsSL https://cf.trackerslist.com/best_aria2.txt || echo "")
            echo "ðŸš€ Starting download..."
            node stream_upload.js
