# CNB 流水线配置 - 磁力链接下载到 OneDrive
# 通过 api_trigger 事件触发

# 匹配所有分支
"**":
  # API 触发事件 - 测试磁力下载
  api_trigger_magnet:
    - name: magnet-download-test
      docker:
        image: node:20-slim
      stages:
        - name: Install aria2
          script: |
            sed -i 's/deb.debian.org/mirrors.cloud.tencent.com/g' /etc/apt/sources.list.d/debian.sources 2>/dev/null || true
            apt-get update && apt-get install -y --no-install-recommends aria2 curl
        
        - name: Download magnet
          script: |
            echo "📡 Fetching trackers..."
            TRACKERS=$(curl -fsSL https://cf.trackerslist.com/best_aria2.txt || echo "")
            echo "Got ${#TRACKERS} bytes of trackers"
            
            echo "🚀 Starting aria2 download..."
            echo "MAGNET: $MAGNET"
            
            mkdir -p /downloads
            aria2c \
              --bt-tracker="$TRACKERS" \
              --file-allocation=none \
              --seed-time=0 \
              --max-connection-per-server=16 \
              --bt-max-peers=100 \
              --summary-interval=5 \
              --dir=/downloads \
              --max-overall-download-limit=0 \
              --bt-stop-timeout=300 \
              "$MAGNET" || echo "Download finished or timeout"
            
            echo "📁 Downloaded files:"
            ls -lah /downloads/
            du -sh /downloads/
